//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prototype.Resources {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Prototype.Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   {0}は必須です。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS001 {
            get {
                return ResourceManager.GetString("MS001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS002 {
            get {
                return ResourceManager.GetString("MS002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}文字以下で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS003 {
            get {
                return ResourceManager.GetString("MS003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}byte以上で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS004 {
            get {
                return ResourceManager.GetString("MS004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は{1}byte以下で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS005 {
            get {
                return ResourceManager.GetString("MS005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英語で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS006 {
            get {
                return ResourceManager.GetString("MS006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS007 {
            get {
                return ResourceManager.GetString("MS007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は半角英数記号で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS008 {
            get {
                return ResourceManager.GetString("MS008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}はyyyy/MM/dd形式の正しい日付で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS009 {
            get {
                return ResourceManager.GetString("MS009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0}は数値形式で入力してください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS010 {
            get {
                return ResourceManager.GetString("MS010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   入力に誤りがあります。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS011 {
            get {
                return ResourceManager.GetString("MS011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   システムエラーが発生しました。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS012 {
            get {
                return ResourceManager.GetString("MS012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   セッションの有効期限が切れています。再度ログインしてください。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string MS013 {
            get {
                return ResourceManager.GetString("MS013", resourceCulture);
            }
        }
    }
}
